spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobscraper_db
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    user: ${SPRING_FLYWAY_USER:root}
    password: ${SPRING_FLYWAY_PASSWORD:password}
  web:
    resources:
      static-locations: classpath:/public

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: OFF



jobs:
  search:
    url: https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search
    keywords: Handläggare OR Administratör
    geoId: 105117694 #Sverige
    places: 103264854,100584176,106138542,112140757 #Stockholm, Uppsala, Enköping, Muskö

    #Sec, Min, Hours, Days of month, Month, Days of week  // * means every, 0 means none
    scheduleWeekdaysCron: 0 0 8,10,12,14,16,18 * * 1-5
    scheduleNightlyCron: 0 0 6 * * 1-5
    scheduleWeekendsCron: 0 0 18 * * 6,7

    weekdaysTimePeriodHours: 2
    nightlyTimePeriodHours: 12
    weekendsTimePeriodHours: 24

# Full search url: https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=Handläggare OR Administratör&geoId=105117694&f_PP=103264854,106138542,104356695,112140757&f_TPR=r7200
# Full url enc: https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=Handl%C3%A4ggare%20OR%20Administrat%C3%B6r&geoId=105117694&f_PP=103264854,106138542,104356695,112140757&f_TPR=r7200